### ISSUE TITLE
Unit Of Work.

### ISSUE THREAD

**Issue by Bartmax** [timschreiber/Mvc5IdentityExample#1]
In this example there's a Unit of work but you are not using it anywhere. It would be great to have it added on one controller so people can see how to use it with the entities. Maybe added a related entity to user that uses the UOW pattern. (or maybe I missed it?)

**Comment by timschreiber** [comment]
You're not looking in the right place. You can find the IUnitOfWork dependency in Mvc5IdentityExample/Mvc5IdentityExample/Mvc5IdentityExample.Web/Identity/UserStore.cs

The purpose of this example was not to show how to use the UnitOfWork pattern -- but rather show that you _can_ use it with ASP.NET Identity. For general info on using the Unit of Work pattern in an ASP.NET MVC application, a good resource is http://www.asp.net/mvc/overview/older-versions/getting-started-with-ef-5-using-mvc-4/implementing-the-repository-and-unit-of-work-patterns-in-an-asp-net-mvc-application.

You will just need to add a IUnitOfWork dependency in the constructor of your Controller and set a Field similarly to how I did it in the UserStore. Unity should handle the rest.

Happy coding!

**Comment by Bartmax** [comment]
I was indeed looking at the wrong place. Thanks. Now I only see that the UOW pattern is not "encouraged" (?).

```
TryDoSomethingAtomic(User user1, User user2) {
    DeleteAsync(user1)
    CreateAsync(user2)
}
```

if CreateAsync fails, the user1 will be deleted because you are calling savechanges on every call and operations won't be atomic. I think that's to mimic the UserStore provided by identity ? Do you think that removing the SaveChanges inside the store and add a UserStore.Commit() method  will be better?

**Comment by timschreiber** [comment]
Why would you say UoW isn't encouraged? Why would I have gone through the effort of implementing ASP.NET Identity with UoW if it isn't encouraged?

As far as adding a "SaveChanges" to the UserStore is concerned, the problem you're going to run into there is the fact that the ASP.NET Identity UserManager class won't see it or be able to use it in any way. UserManager expects an IUser<TUser,TKey>, and there is no SaveChanges method in that interface.

I suppose you could write your own custom UserManager class, but you're looking at a ton of work there.

**Comment by Bartmax** [comment]
I would say that is not 'encouraged' (maybe not the right word, my native isn't english, sorry for that). because the whole purpose of the UOW pattern as far as I know, is that you make the business operations as an atomic transaction (http://martinfowler.com/eaaCatalog/unitOfWork.html). So if operation A fails then all others operations should fail, this is not the case with this implementation.

So if I want to do anything else when creating a user (fill other data on another entity/repository, audit the operation, log, whatever), it won't operate as a single transaction.

Having a SaveChanges method on every call breaks this. If you see the architecture on the link you referenced, the controllers talks directly to the UOW (that's why I first looked up there for it).

Don't get me wrong, I'm not arguing or telling you if it's bad or not, I'm just trying to get all the concepts and understand this, because something does not look like it fits.

After seeing your comment about my suggestion and thinking a little bit more about it, I'm guessing the problem relies on the controller calling directly the UserManager and not the UOW.
Exposing the UserManager from the UOW looks like it will honor the uow pattern but doesn't feel like it should. Not sure.

I will try to investigate more and keep playing with this, because I think that achieving this goal is very important and you made a great contribution to the whole asp.net community because of your blog posts and this repo.

Oh, and last but definitely not least, I'm very grateful for taking your time to read and answer. Thanks.

**update** and example of what I want to achieve:

```
UserManager.CreateAsync(....) // no save changes here.
LogUserCreation(...) // other context, cross cutting concern.
UserManager.DeleteAsync(....) // no save changes here.
LogUserDeletion(...) // other context, cross cutting concern.
DoSomethingElseWithAnotherRepository(...) // no save changes here either. (create files, default categories for user, permissions, data from the create form that doesn't belong to the user entity. , this can be anything).
something.Commit() // create, delete, logs, and something else operations in an atomic fashion. (one fails = all fails)
```

being something the uow, or _maybe_ something else. not sure yet.

**Comment by timschreiber** [comment]
Sounds like you have a plan. Can't hurt to try it, huh?
