### ISSUE TITLE
Missing properties on User <--> IdentityUser

### ISSUE THREAD

**Issue by Bartmax** [timschreiber/Mvc5IdentityExample#2]
I noticed that some properties are left out from User/IUser while there exist on IdentityUser.
Like lockoutEnabled and TwoFactorEnabled and other ones.

Is this intentional? aren't they needed or you are using another version of Identity that I'm using?

**Comment by timschreiber** [comment]
The great thing about ASP.NET Identity is that is kind of a pick-and-choose what you want to support. I chose not to support account locking or two-factor authentication for the purposes of this example. Showing how to use ASP.NET Identity in general is not the intent of this example (there's a great link at the beginning of the first blog post for general ASP.NET Identity help. I never set out to write other people's code for them. I think the most important part of learning is one doing something for themselves. What this example and the related blog posts do is to show how it's possible to achieve persistence ignorance and eliminate the tight coupling to Entity Framework, and to provide a good foundation for developers to build upon.

**Comment by Bartmax** [comment]
Excellent, I wasn't sure why exactly those things were cut off. Thanks for the promptly and quickly response. much appreciated.
