### ISSUE TITLE
Dapper Project

### ISSUE THREAD

**Issue by fireole** [timschreiber/Mvc5IdentityExample#3]
I like this project and was really looking for dapper which i see you have.  I downloaded to check it out and noticed the project is referencing a file ConnectionFactory.cs in the Data.Dapper project which is missing.  Do you have that file by chance?

Thanks

**Comment by timschreiber** [comment]
Sadly, that is an incomplete project that I don't foresee myself finishing
anytime soon due to my day job and a paying side project.
